[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels.set','filepath','/Volumes/EEG2_MARIA/EEG/AXCPT/Analyzed_datasets/Subject_03_JacLoe/');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = eeg_checkset( EEG );
EEG = pop_select( EEG,'nochannel',{'EXG3' 'EXG4' 'GSR1' 'GSR2' 'Erg1' 'Erg2' 'Resp' 'Plet' 'Temp'});
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64','savenew','/Volumes/EEG2_MARIA/EEG/AXCPT/Analyzed_datasets/Subject_03_JacLoe/Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64.set','overwrite','on','gui','off'); 
EEG=pop_chanedit(EEG, 'lookup','/Users/mstavrin/Documents/MATLAB/EEGLAB_WORKSHOP_SML/eeglab_sml_v3/eeglab_sml_v3/plugins/dipfit2.3/standard_BESA/standard-10-5-cap385.elp');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
pop_editoptions( 'option_storedisk', 1, 'option_savetwofiles', 0, 'option_saveversion6', 0, 'option_single', 0, 'option_memmapdata', 0, 'option_eegobject', 0, 'option_computeica', 1, 'option_scaleicarms', 1, 'option_rememberfolder', 1, 'option_donotusetoolboxes', 0, 'option_checkversion', 0, 'option_chat', 0, 'option_cachesize', 49,00 );
ALLEEG = eeg_checkset(ALLEEG); EEG = eeg_retrieve(ALLEEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_runica(EEG, 'extended',1,'interupt','on');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:64] );
EEG = eeg_checkset( EEG );
figure; pop_plottopo(EEG, [1:64] , 'Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64', 0, 'ydir',1);
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_subcomp( EEG, [1], 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew','/Volumes/EEG2_MARIA/EEG/AXCPT/Analyzed_datasets/Subject_03_JacLoe/Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64_pruned_with_ICA.set','saveold','/Volumes/EEG2_MARIA/EEG/AXCPT/Analyzed_datasets/Subject_03_JacLoe/Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64.set','gui','off'); 
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = eeg_checkset( EEG );
figure; pop_plottopo(EEG, [1:64] , 'Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64 pruned with ICA', 0, 'ydir',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'retrieve',1,'study',0); 
EEG = eeg_checkset( EEG );
figure; pop_plottopo(EEG, [1:64] , 'Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64', 0, 'ydir',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'retrieve',2,'study',0); 
EEG = eeg_checkset( EEG );
figure; pop_plottopo(EEG, [1:64] , 'Subject_03_JacLoe_512_ch_DC_epochs_tr2_auto_all_channels64 pruned with ICA', 0, 'ydir',1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'retrieve',1,'study',0); 
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'retrieve',2,'study',0); 
EEG = eeg_checkset( EEG );
pop_selectcomps(EEG, [1:63] );
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 0, 1, 1);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'retrieve',1,'study',0); 
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'retrieve',2,'study',0); 
EEG = eeg_checkset( EEG );
pop_eegplot( EEG, 1, 1, 1);
EEG = pop_biosig('/Volumes/EEG2_MARIA/EEG/AXCPT/Raw_datasets/Subject_04_DiaTho/diamantis.bdf');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'setname','DiaTo','gui','off'); 
EEG = eeg_checkset( EEG );
EEG = pop_resample( EEG, 512);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'setname','DiaToresampled','savenew','/Volumes/EEG2_MARIA/EEG/AXCPT/Raw_datasets/Subject_04_DiaTho/DiaToresampled.set','overwrite','on','gui','off'); 
EEG = eeg_checkset( EEG );
EEG = pop_epoch( EEG, {  '2'  }, [-0.5           5], 'newname', 'DiaToresampled epochs', 'epochinfo', 'yes');
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 3,'gui','off'); 
EEG = eeg_checkset( EEG );
EEG = pop_rmbase( EEG, [-500 -450]);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 4,'savenew','/Volumes/EEG2_MARIA/EEG/AXCPT/Analyzed_datasets/Subject_04_DiaTho/DiaToresampled epochs.set','overwrite','on','gui','off'); 
